FROM oven/bun:1@sha256:0733e50325078969732ebe3b15ce4c4be5082f18c4ac1a0f0ca4839c2e4e42a7

WORKDIR /workspace

COPY web/package.json web/bun.lock ./
COPY web/default/package.json ./default/package.json
COPY web/classic/package.json ./classic/package.json

RUN bun install --frozen-lockfile

COPY web/default ./default

CMD ["sh", "-c", "cd default && bun run dev"]
